// --- RESPONSIBLE : ALBERT
import type { Metadata } from "next";

import { CFormInscription } from "@/app/Component/CInscription";

export const metadata: Metadata = {
  title: "Inscripcion Recojos",
  description: "Generated by create next app",
  icons:""
};

export default function Home() {
  return (
    <main className="main">
      <CFormInscription/>
    </main>
  );
}
